CREATE GROUP dbAdmin;

GRANT ALL ON DATABASE railway_reservation_system TO dbAdmin;

GRANT ALL ON ALL TABLES IN SCHEMA PUBLIC TO dbAdmin;

ALTER ROLE dbAdmin BYPASSRLS;

CREATE USER mno IN GROUP dbAdmin BYPASSRLS PASSWORD 'mno';
CREATE USER pqr IN GROUP dbAdmin BYPASSRLS PASSWORD 'pqr';
