DROP DATABASE project;
CREATE DATABASE project;

DROP ROLE IF EXISTS abc;
DROP ROLE IF EXISTS def;
DROP ROLE IF EXISTS ghi;
DROP ROLE IF EXISTS jkl;
DROP ROLE IF EXISTS mno;
DROP ROLE IF EXISTS pqr;

REVOKE ALL ON DATABASE project FROM users;
REVOKE ALL ON DATABASE project FROM passengers;
REVOKE ALL ON DATABASE project FROM radmin;

DROP ROLE IF EXISTS users;
DROP ROLE IF EXISTS passengers;
DROP ROLE IF EXISTS radmin;
